### ISSUE TITLE
no LICENSE in repo

### ISSUE THREAD

**Issue by jimsalterjrs** [spencerkimball/stargazers#2]
Looking at the source for main.go I see an Apache 2.0 header, but there's no LICENSE actually defined for the project itself.  

Please update with a LICENSE file in the root of the repository for clarity (and to make sure any other content outside the main.go file is explicitly licensed, not just that one file itself).

**Comment by spencerkimball** [comment]
Thanks for the heads up; I added the LICENSE file.
